accounts/urls.py
from django.urls import path, include
from django.views.generic import TemplateView


from django.views.generic import TemplateView
from .views import SaleRecordApi,PackApi,DeliveryResponseApi,CustomerResponseApi, MyPack

app_name='accounts'


urlpatterns = [
   
    path('sale/', SaleRecordApi.as_view(), name='sale-record'),
    path('pack/', PackApi.as_view(), name='pack-record'),
    path('delivery-company/', DeliveryResponseApi.as_view(), name='delivery-company'),
    path('customer-response/', CustomerResponseApi.as_view(), name='user-response'),
    path('my-pack/', MyPack.as_view(template_name="main/pack/customer_response.html"), name='my-pack'),
    path('my-pack/shipped/', MyPack.as_view(template_name="main/pack/shipped.html"), name='my-pack-shipped'),
    path('my-pack/delivered/', MyPack.as_view(template_name="main/pack/delivered.html"), name='my-pack-delivered'),
    path('my-pack/requested/', MyPack.as_view(template_name="main/pack/requested.html"), name='my-pack-requested'),
    path('my-pack/returned/', MyPack.as_view(template_name="main/pack/returned.html"), name='my-pack-returned'),
    
]

cart/urls.py
from django.urls import path, include
from django.views.generic import TemplateView


from .views import CartList,CartUpdateToggle,pay_now,DeliveryTypeApi

app_name='cart'


urlpatterns = [
   
    path('', CartList.as_view(), name='cart'),
    path('update/', CartUpdateToggle.as_view(), name='update'),
    path('delivery-type/', DeliveryTypeApi.as_view(), name='update'),
    path('pay/', pay_now, name='pay'),

    
]

delivery/urls.py
from django.urls import path



from django.views.generic import TemplateView
from .views import (
	checkout_view,
	checkout,
	ApiUserList,
	ApiDeliveryDetail
	
	)


app_name="delivery"
urlpatterns = [
    path('', checkout_view, name='delivery-info'),
	path('pack/checkout/', checkout, name='checkout'),
	path('api/', ApiUserList.as_view(), name='api'),
	path('api/me/', ApiDeliveryDetail.as_view(), name='api-detail'),


	
    
   
]

ojaale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns


from django.views.generic import TemplateView
from cart.views import CartToggle
from user_profile.views import RegisterView
from product.views import index
from major.views import Search
from referal.views import registerview


from rest_framework import routers

router = routers.DefaultRouter()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products')),
    path('delivery/', include('delivery.urls', namespace='delivery')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('record/', include('accounts.urls', namespace='record')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('', include('company.urls', namespace='company')),
    path('referral/', include('referal.urls', namespace='referral')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('profile/', include('user_profile.urls', namespace='profile')),
    path('cart/add_cart/', CartToggle.as_view(), name='add_cart'),
    path('account/register/', RegisterView.as_view(), name='register'),
    path('store/search/', Search.as_view(), name='search'),
    path('policies/learn-more/', TemplateView.as_view(template_name="main/policies.html"), name='learn-more'),
    path('test/test/', TemplateView.as_view(template_name="main/emails/advert-add-product.html"), name='learn-more'),
   path('gift-giving/now/', TemplateView.as_view(template_name="main/squeeze/index.html"), name='learn-more'),
   
    
    path('',index , name='home'),
    
    path('account/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += router.urls

product/urls.py
from django.urls import path

from rest_framework import routers

router = routers.DefaultRouter()


from .views import (
	ProductsList,
	productdetail,
	productcreate_view,
	productupdate_view,
	ApiProductList,
	ApiProductDetail
    

	)
app_name="products"
urlpatterns = [
    path('', ProductsList.as_view(), name='list'),
	
	path('<slug>/',productdetail, name='detail'),
	path ('create/form/', productcreate_view, name='create'),
	path ('<slug>/update/', productupdate_view, name='update'),


	path('api/list/', ApiProductList.as_view(), name='api-list'),
	path('api/detail/<pk>/', ApiProductDetail.as_view(), name='api-detail'),
	#ProductsDetail.as_view(), name='detail'),
    
   
]
urlpatterns += router.urls

delivery/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.
from product.models import Products
from cart.models import Cart
User=settings.AUTH_USER_MODEL

class DeliveryDetails(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    company_name=models.CharField(max_length=100, null=True, blank=True)
    email=models.EmailField()
    country=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    town=models.CharField(max_length=100)
    street=models.CharField(max_length=100)
    number=models.CharField(max_length=11)
    zip_code=models.IntegerField(null=True, blank=True)
    country_code=models.IntegerField(null=True, blank=True, default=234)
    comment=models.TextField(null=True, blank=True)

    def get_absolute_url(self):
      return reverse("delivery:delivery-info")
    

    def __str__(self):
        return self.first_name

product/models.py
from django.db import models
# from django.contrib.postgres.search import SearchVector, SearchQuery
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

from .utils import unique_slug_generator
from company.models import Company

from reviews.models import Review

User=settings.AUTH_USER_MODEL



class ProductQuerySet(models.QuerySet):
  def search(self,query=None):
    qs=self
    if query is not None:
      

      look_up=Q()
      for word in query.split():
        look_up &= (Q(name__icontains=query)|
          Q(brand__icontains=query)|
          Q(color__icontains=query)|
          Q(sub_category__icontains=query)|
          Q(category__iexact=query))


      qs=qs.filter(look_up).distinct()
    return qs
  def cat_search(self,category_search=None):
    qs=self
    if category_search is not None:
      look_up=(Q(category__iexact=category_search)|
      Q(name__icontains=category_search)|
      Q(sub_category__iexact=category_search)|
      Q(description__iexact=category_search))
      qs=qs.filter(look_up).distinct()
    return qs

class ProductManager(models.Manager):
	def get_queryset(self):
		return ProductQuerySet(self.model, using=self._db)

	def search(self,query=None):
		return self.get_queryset().search(query)
  # def cat_search(self,query=None):
	# 	return self.get_queryset().search(category_search)
class Products(models.Model):
    company=models.ForeignKey(Company, on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    category=models.TextField()
    sub_category=models.CharField(max_length=100, null=True,blank=True )
    price=models.IntegerField()
    discount=models.IntegerField(default=0)
    discounted_from=models.IntegerField(null=True,blank=True)
    status=models.CharField(max_length=30, default="New" )
    availability=models.IntegerField(default=0)
    brand=models.CharField(max_length=100)
    size=models.CharField(max_length=100, null=True, blank=True)
    description=models.TextField()
    color=models.CharField(max_length=30,null=True, blank=True)
    rating=models.FloatField(default=0)
    image=models.FileField(upload_to='product/image')
    timestamp=models.DateTimeField(auto_now_add=True)
    slug=models.SlugField(null=True, blank=True)

    objects=ProductManager()

    class Meta:
      ordering=["-timestamp"]


    def __str__(self):
      return self.name
    
    def get_absolute_url(self):
      return reverse("products:detail", kwargs={'slug':self.slug})
    
    @property
    def get_content_type(self):
      instance=self
      content_type=ContentType.objects.get_for_model(instance.__class__)
      return content_type


class ProductImages(models.Model):
  product=models.ForeignKey(Products, on_delete=models.CASCADE)
  image=models.ImageField(upload_to='product/images')
  alt=models.CharField(max_length=200, null=True, blank=True)
  def __str__(self):
      return str(self.product.name) + str(self.id)

class ProductPriceRanges(models.Model):
  product=models.ForeignKey(Products, on_delete=models.CASCADE)
  start_quantity=models.IntegerField()
  stop_quantity=models.IntegerField()
  price=models.DecimalField(max_digits=20, decimal_places=2)

  def __str__(self):
      return str(self.product.name) + str(self.id)

class ProductVariant(models.Model):
  product=models.ForeignKey(Products, on_delete=models.CASCADE)
  
  def __str__(self):
      return str(self.product.name) + str(self.id)

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
	instance.name = instance.name.capitalize()
	if not instance.slug:
		instance.slug =unique_slug_generator(instance)
pre_save.connect(rl_pre_save_receiver, sender=Products)

delivery/forms.py
from django import forms
from .models import DeliveryDetails

class CheckoutForm(forms.ModelForm):
    first_name=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'First Name'}))
    class Meta:

        model=DeliveryDetails
        fields=(
            'first_name',
            'last_name',
            'email',
            'country',
            'state',
            'town',
            'street',
            'number',
            'comment',

        )
        widgets={
            'first_name':forms.TextInput(attrs={'placeholder':'First Name'}),
            'last_name':forms.TextInput(attrs={'placeholder':'Last Name'}),
            'email':forms.TextInput(attrs={'placeholder':'Email Name'}),
            'country':forms.TextInput(attrs={'placeholder':'Country Name'}),
            'state':forms.TextInput(attrs={'placeholder':'State Name'}),
            'town':forms.TextInput(attrs={'placeholder':'Town Name'}),
            'street':forms.TextInput(attrs={'placeholder':'Street '}),
            'number':forms.TextInput(attrs={'placeholder':'Phone Number'}),
            'comment':forms.TextInput(attrs={'placeholder':'Comment (optional)'}),
        }


    

product/forms.py
from django import forms
from .models import Products
CATEGORY_CHOICES =( ("New", "New Product"), ("Used", "Fairly Used Product")) 
class ProductForm(forms.ModelForm):

    # # creating a form  
    status = forms.ChoiceField(choices = CATEGORY_CHOICES) 
    class Meta:

        model=Products
        fields=(
            'name',
            'price',
            'discounted_from',
            'availability',
            "status",
            'brand',
            'size',
            'description',
            'color',
            'image',
        )
        widgets={
            'name':forms.TextInput(attrs={'placeholder':'Product Name'}),
            # 'category':forms.ChoiceField(choices = CATEGORY_CHOICES),
            # 'sub_category':forms.TextInput(attrs={'placeholder':'Sub Category'}),
            'price':forms.TextInput(attrs={'placeholder':'Price'}),
            'discounted_from':forms.TextInput(attrs={'placeholder':'Former Price'}),
            'availability':forms.TextInput(attrs={'placeholder':'Availability'}),
            'brand':forms.TextInput(attrs={'placeholder':'Brand'}),
            'size':forms.TextInput(attrs={'placeholder':'Size e.g S, M, L, 41,42 ...'}),
            'color':forms.TextInput(attrs={'placeholder':'Color'}),
        }


    

delivery/views.py
# API
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import viewsets, renderers
from rest_framework.decorators import action

from .serializers import DeliverySerializers, UserSerializers


#PYTHON
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect,Http404
from django.contrib import messages
from .forms import CheckoutForm
from .models import DeliveryDetails
from django.contrib.auth import get_user_model

from django.contrib.auth.decorators import login_required

from cart.models import Cart
from company.models import Company
from referal.models import Referral
# Create your views here.
context={}

@login_required()
def checkout_view(request):
  
    user_details=DeliveryDetails.objects.filter(user=request.user)
    if user_details:
      obj = get_object_or_404(DeliveryDetails, user=request.user)
      form = CheckoutForm(request.POST or None, instance = obj)
    else:
      form = CheckoutForm(request.POST or None)
    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(f'/delivery/pack/checkout/')
        
    if form.errors:
        print(form.errors)
        context={"form":form}
    cart_=get_object_or_404(Cart, user=request.user)
    total=0
    # for product in cart_.products.all():
    #     price = product.price
    #     total= price + total
    # cart_.total=total
    # cart_.save()
    context={
    "form":form, 
    # 'subtotal':total
    }
    template_name='main/delivery/checkout_detail.html'
    return render(request, template_name,context)
  
# # update view for details 
# def update_view(request, id): 
#     # dictionary for initial data with  
#     # field names as keys 
#     context ={} 
  
#     # fetch the object related to passed id 
#     obj = get_object_or_404(GeeksModel, id = id) 
  
#     # pass the object as instance in form 
#     form = GeeksForm(request.POST or None, instance = obj) 
  
#     # save the data from the form and 
#     # redirect to detail_view 
#     if form.is_valid(): 
#         form.save() 
#         return HttpResponseRedirect("/"+id) 
  
#     # add form dictionary to context 
#     context["form"] = form 
  
#     return render(request, "update_view.html", context) 

@login_required()
def checkout(request):
    cart_=get_object_or_404(Cart, user=request.user)
    delivery=get_object_or_404(DeliveryDetails, user=request.user)
    companys=Company.objects.filter(products__salerecord__in=cart_.content.all()).distinct()
    
    delivery_price_list=[x.average_delivery_cost for x in companys]
    # delivery_price_list=[x.product.company.filter().distinct() for x in cart_.content.all()]
    delivery_price=sum(delivery_price_list)
    

        
    

    
    
    context={
        "delivery":delivery,
        "delivery_price" :delivery_price,
        'cart':cart_
        }
    
    template_name='main/delivery/checkout.html'
    return render(request, template_name,context)





#Api Views-------------------------------------------------------------------------------------------------


User=get_user_model()
class ApiUserList(APIView):
    """
    List all users, or create a new user.
    """

    def get(self, request, format=None):
        users = User.objects.all()
        serializer = UserSerializers(users, many=True)
        return Response(serializer.data)

    
class ApiDeliveryDetail(APIView):
    """
    Retrieve, update or delete a snippet instance.
    """
    def get_object(self):
        try:
            return DeliveryDetails.objects.get(user=self.request.user)
        except DeliveryDetails.DoesNotExist:
            raise Http404

    def get(self, request, format=None):
        delivery = self.get_object()
        serializer = DeliverySerializers(delivery)
        return Response(serializer.data)

    def put(self, request, format=None):
        delivery = self.get_object()
        serializer = DeliverySerializer(delivery, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    

product/templates/main/delivery/checkout_detail.html
{% extends 'main/base.html' %}
{% block content %}
{{block.super}}
<div class="cart-table-area section-padding-100">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-lg-8">
                <div class="checkout_details_area mt-50 clearfix">

                    <div class="cart-title">
                        <h2>Delivery Details</h2>
                    </div>

                    <form action="." method="post" class="checkout_form">
                        {% csrf_token %}
                        <div class="row">
                            
                            <div class="col-12 mb-3">
                                {{form}}
                            </div>
                           
            

                            <div class="col-12">
                                <div class="custom-control custom-checkbox d-block mb-2">
                                    <input type="checkbox" class="custom-control-input" id="customCheck2">
                                    <label class="custom-control-label" for="customCheck2">Create an accout</label>
                                </div>
                                <div class="custom-control custom-checkbox d-block">
                                    <input type="checkbox" class="custom-control-input" id="customCheck3">
                                    <label class="custom-control-label" for="customCheck3">Ship to a different address</label>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn amado-btn w-100">Checkout</button>
                    </form>
                </div>
            </div>
            <div class="col-12 col-lg-4">
                <div class="cart-summary">
                    <h5>Cart Total</h5>
                    <ul class="summary-table">
                        <li><span>subtotal:</span> <span>&#8358;{{user.cart.total}}.00</span></li>
                        <li><span>delivery type:</span> <span >{{user.cart.delivery_type | title}}</span></li>
        
                        <li><span>delivery:</span> <span >Undefined</span></li>
                        {% comment %} <li><span>gift card:</span> <span>&#8358;{{request.user.userprofile.gift_card}}</span></li> {% endcomment %}
                        <input type="hidden" id="priceSubtotal" name="price"  value="{{user.cart.total}}">
                        {% comment %} <input type="hidden" id="giftTotal" name="price"  value="{{request.user.userprofile.gift_card}}"> {% endcomment %}
                        <li><span>total:</span> <span >Undefined</span></li>
                    </ul>


                  
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}
{% block formadjust %}
<script type="text/javascript">
    $('document').ready(function(){
        $('.checkout_form input').addClass('form-control');
        $('.checkout_form input').css('margin-bottom','10px');
        $('.checkout_form li').css('color','red');
        $('.checkout_form label').css('display','none');
        $('#id_comment').addClass('.w-100')
    })
</script>
<script src="https://js.paystack.co/v1/inline.js"></script>
<div id="paystackEmbedContainer"></div>


<script>
    var request = new XMLHttpRequest();

request.open('POST', 'https://api.kwik.delivery/create_task_via_vendor');

request.setRequestHeader('Content-Type', 'application/json');

request.onreadystatechange = function () {
if (this.readyState === 4) {
console.log('Status:', this.status);
console.log('Headers:', this.getAllResponseHeaders());
console.log('Body:', this.responseText);
}
};

var body = {
'domain_name': 'dev-client-panel.kwik.delivery',
'access_token': '3b6220eb66129f2fc06281a9901aecda',
'vendor_id': 151,
'is_multiple_tasks': 1,
'fleet_id': '',
'latitude': 0,
'longitude': 0,
'timezone': -330,
'has_pickup': 1,
'has_delivery': 1,
'pickup_delivery_relationship': 0,
'layout_type': 0,
'auto_assignment': 1,
'team_id': '',
'pickups': [
{
  'address': 'Delhi Cantonment, New Delhi, Delhi, India',
  'name': 'Corporate Grg',
  'latitude': 28.5961279,
  'longitude': 77.15873750000003,
  'time': '2019-09-03 11:52:56',
  'phone': '+917654323456',
  'template_data': [
    {
      'label': 'baseFare',
      'data_type': 'Number',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 40,
      'input': 40,
      'template_id': 'pricing-template',
      'display_name': 'baseFare'
    },
    {
      'label': 'timeFare',
      'display_name': 'timeFare',
      'data_type': 'Number',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 2,
      'input': 2,
      'template_id': 'pricing-template'
    },
    {
      'label': 'distanceFare',
      'display_name': 'distanceFare',
      'data_type': 'Number',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 1,
      'input': 1,
      'template_id': 'pricing-template'
    },
    {
      'label': 'pricingType',
      'display_name': 'pricingType',
      'data_type': 'Text',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 'Variable',
      'input': 'Variable',
      'template_id': 'pricing-template'
    },
    {
      'label': 'insuranceAmount',
      'display_name': 'insuranceAmount',
      'data_type': 'Number',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 0,
      'input': 0,
      'template_id': 'pricing-template'
    }
  ],
  'template_name': 'pricing-template',
  'ref_images': '',
  'email': 'co@yopmail.com'
}
],
'deliveries': [
{
  'address': 'CDCL, Madhya Marg, 28B, Sector 28B, Chandigarh, India',
  'name': 'Ishita',
  'latitude': 30.7188978,
  'longitude': 76.81029809999995,
  'time': '2019-09-03T16:26:23.000Z',
  'phone': '+916543212345',
  'template_data': [
    {
      'label': 'baseFare',
      'data_type': 'Number',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 40,
      'input': 40,
      'template_id': 'pricing-template',
      'display_name': 'baseFare'
    },
    {
      'label': 'timeFare',
      'display_name': 'timeFare',
      'data_type': 'Number',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 2,
      'input': 2,
      'template_id': 'pricing-template'
    },
    {
      'label': 'distanceFare',
      'display_name': 'distanceFare',
      'data_type': 'Number',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 1,
      'input': 1,
      'template_id': 'pricing-template'
    },
    {
      'label': 'pricingType',
      'display_name': 'pricingType',
      'data_type': 'Text',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 'Variable',
      'input': 'Variable',
      'template_id': 'pricing-template'
    },
    {
      'label': 'insuranceAmount',
      'display_name': 'insuranceAmount',
      'data_type': 'Number',
      'app_side': '2',
      'required': 0,
      'value': 0,
      'data': 0,
      'input': 0,
      'template_id': 'pricing-template'
    }
  ],
  'template_name': 'pricing-template',
  'ref_images': '',
  'has_return_task': false,
  'is_package_insured': 0,
  'hadVairablePayment': 1,
  'hadFixedPayment': 0
}
],
'insurance_amount': 0,
'total_no_of_tasks': 1,
'total_service_charge': 23,
'payment_method': 8,
'amount': '841.62'
};
var amountSubtotal= $('#priceSubtotal').val()
var giftTotal= $('#giftTotal').val()
var deliveryCharge=body.amount 
var amountTotal= parseInt(amountSubtotal) + parseInt(deliveryCharge)-parseInt(giftTotal)
console.log(deliveryCharge)
$('#deliveryCharge').append(body.amount)
$('#TotalPrice').append(amountTotal)

request.send(JSON.stringify(body));
</script>
<script>
var request = new XMLHttpRequest();

request.open('POST', 'https://api.kwik.delivery/send_payment_for_task');

request.setRequestHeader('Content-Type', 'application/json');

request.onreadystatechange = function () {
  if (this.readyState === 4) {
    console.log('Status:', this.status);
    console.log('Headers:', this.getAllResponseHeaders());
    console.log('Body:', this.responseText);
  }
};
var phoneNumber= $('#id_number').val()
var customerCountry= $('#id_country').val()
var customerState= $('#id_state').val()
var customerLga= $('#id_town').val()
var customerStreet= $('#id_street').val()
var addressCustomer= customerStreet + ', ' + customerLga + ', ' + customerState + ', ' + customerCountry
console.log(addressCustomer)
var body = {
  'custom_field_template': 'pricing-template',
  'access_token': '789ac4828a1dcf99a893557a72d95571',
  'domain_name': 'test-client-panel.kwik.delivery',
  'timezone': -330,
  'vendor_id': 162,
  'is_multiple_tasks': 1,
  'layout_type': 0,
  'pickup_custom_field_template': 'pricing-template',
  'deliveries': [
    {
      'address': 'Sector 19, Chandigarh, India',
      'name': '',
      'latitude': 30.72936309999999,
      'longitude': 76.79197279999994,
      'time': '2019-09-03 12:48:24',
      'phone': '+919646297487',
      'has_return_task': false,
      'is_package_insured': 0
    }
  ],
  'has_pickup': 1,
  'has_delivery': 1,
  'auto_assignment': 1,
  'user_id': 1,
  'pickups': [
    {
      'address': 'CDCL, Madhya Marg, 28B, Sector 28B, Chandigarh, India',
      'name': 'Jovani Predovic',
      'latitude': 30.7188978,
      'longitude': 76.81029809999995,
      'time': '2019-09-03 12:48:24',
      'phone': '+917837905578',
      'email': 'lead@yopmail.com'
    }
  ],
  'payment_method': 32,
  'form_id': 2
};

request.send(JSON.stringify(body));
</script>
<!-- <script>
    function payWithPaystack(){
      var handler = PaystackPop.setup({
        key: 'pk_test_37594665d8156eff9f674d8fe0ee495ba71fc61a',
        email: 'customer@email.com',
        amount: 10000,
        currency: "NGN",
        ref: ''+Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
        firstname: 'Stephen',
        lastname: 'King',
        // label: "Optional string that replaces customer email"
        metadata: {
           custom_fields: [
              {
                  display_name: "Mobile Number",
                  variable_name: "mobile_number",
                  value: "+2348012345678"
              }
           ]
        },
        callback: function(response){
            alert('success. transaction ref is ' + response.reference);
        },
        onClose: function(){
            alert('window closed');
        }
      });
      handler.openIframe();
    }
</script> -->
{% endblock formadjust %}
<!-- <form >
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <button type="button" onclick="payWithPaystack()"> Pay </button> 
  </form>
   
  <script>
    function payWithPaystack(){
      var handler = PaystackPop.setup({
        key: 'pk_test_86d32aa1nV4l1da7120ce530f0b221c3cb97cbcc',
        email: 'customer@email.com',
        amount: 10000,
        currency: "NGN",
        ref: ''+Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
        firstname: 'Stephen',
        lastname: 'King',
        // label: "Optional string that replaces customer email"
        metadata: {
           custom_fields: [
              {
                  display_name: "Mobile Number",
                  variable_name: "mobile_number",
                  value: "+2348012345678"
              }
           ]
        },
        callback: function(response){
            alert('success. transaction ref is ' + response.reference);
        },
        onClose: function(){
            alert('window closed');
        }
      });
      handler.openIframe();
    }
  </script> -->
  

product/templates/main/delivery/pay.html
{% extends 'main/base.html' %}
{% block content %}
<section class="courses">
  <div class="row ">
 
      <div class="col-12">
<div style="width: 100%;">

  <script src="https://js.paystack.co/v1/inline.js"></script>
  <div id="paystackEmbedContainer"></div>
</div>
      </div>
      </div>

</section>
{% endblock content %}
{% block formadjust %}
<script type="text/javascript">
var cartAmmount=parseInt("{{cart.total}}");
var endpoint="127.0.0.1:8000"+"/record/pack/";
         var record={
          "id": 1,
        "contents": [
           0
        ],
        "total_price": 0,
        "user": 1,
           "csrfmiddlewaretoken":"{{csrf_token}}"
         };
 
         $.ajax({
                 type:'POST',
                 url:"127.0.0.1:8000/record/pack/",
                 data:record,
                 success:function(data){
                   alert('successfully added')
                 },
                 error:function(err){
                     alert('error :'+err);
                 }
                 
             });
PaystackPop.setup({
    key: 'pk_test_37594665d8156eff9f674d8fe0ee495ba71fc61a',
    email: '{{cart.user.email}}',
    amount: cartAmmount+"00",
    container: 'paystackEmbedContainer',
    callback: function(response){
         
         var endpoint="127.0.0.1:8000"+"/record/pack/";
         var record={
          "id": 1,
        "contents": [
           0
        ],
        "total_price": 0,
        "user": 1,
           "csrfmiddlewaretoken":"{{csrf_token}}"
         };
 
         $.ajax({
                 type:'POST',
                 url:endpoint,
                 data:record,
                 success:function(data){
                   alert('successfully added')
                 },
                 error:function(){
                     alert('error ');
                 }
                 
             });
             alert('successfully subscribed. transaction ref is ' + response.reference+ endpoint);
     },
   });
   </script>
   <script type="text/javascript">
   $('document').ready(function(){
       $(".head-nav ul").css("display", "none");
       $("#responsive-nav").css("display", "none");
       $(".mobile-nav").css("display", "none");
       

    });
   </script>
   {% endblock formadjust %}