accounts/urls.py
from django.urls import path, include
from django.views.generic import TemplateView


from django.views.generic import TemplateView
from .views import SaleRecordApi,PackApi,DeliveryResponseApi,CustomerResponseApi, MyPack

app_name='accounts'


urlpatterns = [
   
    path('sale/', SaleRecordApi.as_view(), name='sale-record'),
    path('pack/', PackApi.as_view(), name='pack-record'),
    path('delivery-company/', DeliveryResponseApi.as_view(), name='delivery-company'),
    path('customer-response/', CustomerResponseApi.as_view(), name='user-response'),
    path('my-pack/', MyPack.as_view(template_name="main/pack/customer_response.html"), name='my-pack'),
    path('my-pack/shipped/', MyPack.as_view(template_name="main/pack/shipped.html"), name='my-pack-shipped'),
    path('my-pack/delivered/', MyPack.as_view(template_name="main/pack/delivered.html"), name='my-pack-delivered'),
    path('my-pack/requested/', MyPack.as_view(template_name="main/pack/requested.html"), name='my-pack-requested'),
    path('my-pack/returned/', MyPack.as_view(template_name="main/pack/returned.html"), name='my-pack-returned'),
    
]

cart/urls.py
from django.urls import path, include
from django.views.generic import TemplateView


from .views import CartList,CartUpdateToggle,pay_now,DeliveryTypeApi

app_name='cart'


urlpatterns = [
   
    path('', CartList.as_view(), name='cart'),
    path('update/', CartUpdateToggle.as_view(), name='update'),
    path('delivery-type/', DeliveryTypeApi.as_view(), name='update'),
    path('pay/', pay_now, name='pay'),

    
]

ojaale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns


from django.views.generic import TemplateView
from cart.views import CartToggle
from user_profile.views import RegisterView
from product.views import index
from major.views import Search
from referal.views import registerview


from rest_framework import routers

router = routers.DefaultRouter()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products')),
    path('delivery/', include('delivery.urls', namespace='delivery')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('record/', include('accounts.urls', namespace='record')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('', include('company.urls', namespace='company')),
    path('referral/', include('referal.urls', namespace='referral')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('profile/', include('user_profile.urls', namespace='profile')),
    path('cart/add_cart/', CartToggle.as_view(), name='add_cart'),
    path('account/register/', RegisterView.as_view(), name='register'),
    path('store/search/', Search.as_view(), name='search'),
    path('policies/learn-more/', TemplateView.as_view(template_name="main/policies.html"), name='learn-more'),
    path('test/test/', TemplateView.as_view(template_name="main/emails/advert-add-product.html"), name='learn-more'),
   path('gift-giving/now/', TemplateView.as_view(template_name="main/squeeze/index.html"), name='learn-more'),
   
    
    path('',index , name='home'),
    
    path('account/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += router.urls

product/urls.py
from django.urls import path

from rest_framework import routers

router = routers.DefaultRouter()


from .views import (
	ProductsList,
	productdetail,
	productcreate_view,
	productupdate_view,
	ApiProductList,
	ApiProductDetail
    

	)
app_name="products"
urlpatterns = [
    path('', ProductsList.as_view(), name='list'),
	
	path('<slug>/',productdetail, name='detail'),
	path ('create/form/', productcreate_view, name='create'),
	path ('<slug>/update/', productupdate_view, name='update'),


	path('api/list/', ApiProductList.as_view(), name='api-list'),
	path('api/detail/<pk>/', ApiProductDetail.as_view(), name='api-detail'),
	#ProductsDetail.as_view(), name='detail'),
    
   
]
urlpatterns += router.urls

product/models.py
from django.db import models
# from django.contrib.postgres.search import SearchVector, SearchQuery
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

from .utils import unique_slug_generator
from company.models import Company

from reviews.models import Review

User=settings.AUTH_USER_MODEL



class ProductQuerySet(models.QuerySet):
  def search(self,query=None):
    qs=self
    if query is not None:
      

      look_up=Q()
      for word in query.split():
        look_up &= (Q(name__icontains=query)|
          Q(brand__icontains=query)|
          Q(color__icontains=query)|
          Q(sub_category__icontains=query)|
          Q(category__iexact=query))


      qs=qs.filter(look_up).distinct()
    return qs
  def cat_search(self,category_search=None):
    qs=self
    if category_search is not None:
      look_up=(Q(category__iexact=category_search)|
      Q(name__icontains=category_search)|
      Q(sub_category__iexact=category_search)|
      Q(description__iexact=category_search))
      qs=qs.filter(look_up).distinct()
    return qs

class ProductManager(models.Manager):
	def get_queryset(self):
		return ProductQuerySet(self.model, using=self._db)

	def search(self,query=None):
		return self.get_queryset().search(query)
  # def cat_search(self,query=None):
	# 	return self.get_queryset().search(category_search)
class Products(models.Model):
    company=models.ForeignKey(Company, on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    category=models.TextField()
    sub_category=models.CharField(max_length=100, null=True,blank=True )
    price=models.IntegerField()
    discount=models.IntegerField(default=0)
    discounted_from=models.IntegerField(null=True,blank=True)
    status=models.CharField(max_length=30, default="New" )
    availability=models.IntegerField(default=0)
    brand=models.CharField(max_length=100)
    size=models.CharField(max_length=100, null=True, blank=True)
    description=models.TextField()
    color=models.CharField(max_length=30,null=True, blank=True)
    rating=models.FloatField(default=0)
    image=models.FileField(upload_to='product/image')
    timestamp=models.DateTimeField(auto_now_add=True)
    slug=models.SlugField(null=True, blank=True)

    objects=ProductManager()

    class Meta:
      ordering=["-timestamp"]


    def __str__(self):
      return self.name
    
    def get_absolute_url(self):
      return reverse("products:detail", kwargs={'slug':self.slug})
    
    @property
    def get_content_type(self):
      instance=self
      content_type=ContentType.objects.get_for_model(instance.__class__)
      return content_type


class ProductImages(models.Model):
  product=models.ForeignKey(Products, on_delete=models.CASCADE)
  image=models.ImageField(upload_to='product/images')
  alt=models.CharField(max_length=200, null=True, blank=True)
  def __str__(self):
      return str(self.product.name) + str(self.id)

class ProductPriceRanges(models.Model):
  product=models.ForeignKey(Products, on_delete=models.CASCADE)
  start_quantity=models.IntegerField()
  stop_quantity=models.IntegerField()
  price=models.DecimalField(max_digits=20, decimal_places=2)

  def __str__(self):
      return str(self.product.name) + str(self.id)

class ProductVariant(models.Model):
  product=models.ForeignKey(Products, on_delete=models.CASCADE)
  
  def __str__(self):
      return str(self.product.name) + str(self.id)

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
	instance.name = instance.name.capitalize()
	if not instance.slug:
		instance.slug =unique_slug_generator(instance)
pre_save.connect(rl_pre_save_receiver, sender=Products)

product/forms.py
from django import forms
from .models import Products
CATEGORY_CHOICES =( ("New", "New Product"), ("Used", "Fairly Used Product")) 
class ProductForm(forms.ModelForm):

    # # creating a form  
    status = forms.ChoiceField(choices = CATEGORY_CHOICES) 
    class Meta:

        model=Products
        fields=(
            'name',
            'price',
            'discounted_from',
            'availability',
            "status",
            'brand',
            'size',
            'description',
            'color',
            'image',
        )
        widgets={
            'name':forms.TextInput(attrs={'placeholder':'Product Name'}),
            # 'category':forms.ChoiceField(choices = CATEGORY_CHOICES),
            # 'sub_category':forms.TextInput(attrs={'placeholder':'Sub Category'}),
            'price':forms.TextInput(attrs={'placeholder':'Price'}),
            'discounted_from':forms.TextInput(attrs={'placeholder':'Former Price'}),
            'availability':forms.TextInput(attrs={'placeholder':'Availability'}),
            'brand':forms.TextInput(attrs={'placeholder':'Brand'}),
            'size':forms.TextInput(attrs={'placeholder':'Size e.g S, M, L, 41,42 ...'}),
            'color':forms.TextInput(attrs={'placeholder':'Color'}),
        }


    

product/templates/main/pack/customer_response.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
{{block.super}}

<div class="single-product-area detail-section section-padding-100 clearfix">
    <div class="container-fluid">
       
        <div id="breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    
                    <li  style="padding:10px; "><a href="{% url 'accounts:my-pack' %}" class="active" style="color: rgb(243, 162, 55);">All Orders |</a> </li>
                    <li style="padding:10px;"><a href="{% url 'accounts:my-pack-requested' %}" >Requested orders |</a></li>
                    <li style="padding:10px;" ><a href="{% url 'accounts:my-pack-shipped' %}">Shiped orders |</a></li>
                    <li style="padding:10px;"><a href="{% url 'accounts:my-pack-delivered' %}">Delivered orders |</a></li>
                    <li style="padding:10px;"><a href="{% url 'accounts:my-pack-returned' %}">Returned orders</a></li>
                </ul>
            </div>
        </div>
        
       
        {% for obj in user.salerecord_set.all %}
        {% if obj.paid %}
        
        <div id="breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    
                    <li class="active">{{obj.product.name| title}}</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-7">
                <div class="single_product_thumb">
                    <div id="product_details_slider" class="carousel slide" data-ride="carousel">
                      
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                    <img class="gallery_img d-block w-100" style="height: 300px;" src="{{obj.product.image.url}}" alt="{{obj.product.name}}">
                               
                            </div>
                          
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-5">
                <div class="single_product_desc">
                    <!-- Product Meta Data -->
                    <div class="product-meta-data">
                        <div class="line"></div>
                        
                            <h3 style="display: inline;">Package Number: {{obj.package_number}}</h3>
                       
                        <div class="line"></div>
                        <h3 class="">&#8358;{{obj.price}} </h3>
                        <h5 class="product-price">Quantity Requested: {{obj.quantity}} </h5>
                        <h5 class="product-price">Size Requested: {{obj.size}} </h5>
                        <h5 class="product-price">Color Requested: {{obj.color}} </h5>
                        
                      
                        <!-- Avaiable -->
                        <p class="avaibility"><a href="/{{obj.product.company.slug}}">Sold by : {{obj.product.company.name}}</a></p><br/>
                        <h6 class="text-muted">Requested On: {{obj.package_time}} </h6>
                        {% if obj.status == 'delivered' %}
                        <h6 class="text-muted">Delivered On: {{obj.delivery_time}} </h6>
                        {% elif obj.status == 'returned' %}
                        <h6 class="text-muted">Returned On: {{obj.returned_time}} </h6>
                        {% elif obj.status == 'shipped' %}
                        <h6 class="text-muted">Shipped On: {{obj.collected_time}} </h6>
                        {% endif %}
                    </div>


                
                    
      
                    
                       
                        <form class="cart clearfix cart-form" method="post" action="{% url 'add_cart' %}" >{% csrf_token %}
                           {% if obj.status == 'returned' %}
                            <button class="primary-btn add-to-cart " onclick="event.preventDefault()">Status: {{obj.status| title}} </button>
  
                            {% elif obj.status == 'shipped' %}
                            <button class="primary-btn add-to-cart accept-btn">Accept It</button>
                            <input type="hidden" id="saleId" value="{{obj.id}}" />
                            <button class="main-btn  add-to-cart return-btn" >Returned</button>
                            {% endif %}
                        </form>
                        
                    
                       <p>Your order would be delivered within five (5) working days</p>

                      
                    
                    

                </div>
            </div>
        </div>
       
        {% endif %}
        {% endfor %}
        
       
      
    </div>
    </div>

    {% endblock content %}
    {% block formadjust %}
<script type="text/javascript">
    $('document').ready(function(){
        var saleId=$("#saleId").val();
        $('.cart-form .accept-btn').on("click", function(event){
            event.preventDefault();
            datum={
                "status":"accepted",
                "sale_id":saleId,
                "csrfmiddlewaretoken":"{{csrf_token}}"
            }
            myRespond(datum);
        });
        $('.cart-form .return-btn').on("click", function(event){
            event.preventDefault();
            datum={
                "status":"rejected",
                "sale_id":saleId,
                "csrfmiddlewaretoken":"{{csrf_token}}"
            }
            myRespond(datum);
        });
        function myRespond(datum){
          
            $.ajax({
                 type:'POST',
                 url:"/record/customer-response/",
                 data:datum,
                 success:function(data){
                   alert('successfully: The Product Has Been'+data.status)
                 },
                 error:function(err){
                     alert('error :'+err);
                 }
                 
             });
        }
        
    })
</script>
{% endblock formadjust %}

product/templates/main/pack/delivered.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
{{block.super}}

<div class="single-product-area detail-section section-padding-100 clearfix">
    <div class="container-fluid">
       
        <div id="breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    
                    <li  style="padding:10px; "><a href="{% url 'accounts:my-pack' %}" class="active" >All Orders |</a> </li>
                    <li style="padding:10px;"><a href="{% url 'accounts:my-pack-requested' %}">Requested orders |</a></li>
                    <li style="padding:10px;" ><a href="{% url 'accounts:my-pack-shipped' %}">Shiped orders |</a></li>
                    <li style="padding:10px;"><a href="{% url 'accounts:my-pack-delivered' %}" style="color: rgb(243, 162, 55);">Delivered orders |</a></li>
                    <li style="padding:10px;"><a href="{% url 'accounts:my-pack-returned' %}">Returned orders</a></li>
                </ul>
            </div>
        </div>
       
        {% for obj in user.salerecord_set.all %}
        {% if obj.paid %}
        {% if obj.status == "delivered" %}
        <div id="breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    
                    <li class="active">{{obj.product.name| title}}</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-7">
                <div class="single_product_thumb">
                    <div id="product_details_slider" class="carousel slide" data-ride="carousel">
                      
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                    <img class="gallery_img d-block w-100" style="height: 300px;" src="{{obj.product.image.url}}" alt="{{obj.product.name}}">
                               
                            </div>
                          
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-5">
                <div class="single_product_desc">
                    <!-- Product Meta Data -->
                    <div class="product-meta-data">
                        <div class="line"></div>
                        
                            <h3 style="display: inline;">Package Number: {{obj.package_number}}</h3>
                       
                        <div class="line"></div>
                        <h3 class="">&#8358;{{obj.price}} </h3>
                        <h5 class="product-price">Quantity Requested: {{obj.quantity}} </h5>
                        <h5 class="product-price">Size Requested: {{obj.size}} </h5>
                        <h5 class="product-price">Color Requested: {{obj.color}} </h5>
                        
                      
                        <!-- Avaiable -->
                        <p class="avaibility"><a href="/{{obj.product.company.slug}}">Sold by : {{obj.product.company.name}}</a></p><br/>
                        <h6 class="text-muted">Requested On: {{obj.package_time}} </h6>
                        {% if obj.status == 'delivered' %}
                        <h6 class="text-muted">Delivered On: {{obj.delivery_time}} </h6>
                        {% elif obj.status == 'returned' %}
                        <h6 class="text-muted">Returned On: {{obj.returned_time}} </h6>
                        {% elif obj.status == 'shipped' %}
                        <h6 class="text-muted">Shipped On: {{obj.shipped_time}} </h6>
                        {% endif %}
                    </div>


                
                    
      
                    
                       
                        <form class="cart clearfix cart-form" method="post" action="{% url 'add_cart' %}" >{% csrf_token %}
                           {% if obj.status == 'returned' %}
                            <button class="primary-btn add-to-cart " onclick="event.preventDefault()">Status: {{obj.status| title}} </button>
  
                            {% elif obj.status == 'shipped' %}
                            <button class="primary-btn add-to-cart accept-btn">Accept It</button>
                            <input type="hidden" id="saleId" value="{{obj.id}}" />
                            <button class="main-btn  add-to-cart return-btn" >Returned</button>
                            {% endif %}
                        </form>
                        
                    
                       

                      
                    
                    

                </div>
            </div>
        </div>
        {% endif %}
        {% endif %}
        {% endfor %}
    </div>
    </div>

    {% endblock content %}
    {% block formadjust %}
<script type="text/javascript">
    $('document').ready(function(){
        var saleId=$("#saleId").val();
        $('.cart-form .accept-btn').on("click", function(event){
            event.preventDefault();
            datum={
                "status":"accepted",
                "sale_id":saleId,
                "csrfmiddlewaretoken":"{{csrf_token}}"
            }
            myRespond(datum);
        });
        $('.cart-form .return-btn').on("click", function(event){
            event.preventDefault();
            datum={
                "status":"rejected",
                "sale_id":saleId,
                "csrfmiddlewaretoken":"{{csrf_token}}"
            }
            myRespond(datum);
        });
        function myRespond(datum){
          
            $.ajax({
                 type:'POST',
                 url:"/record/customer-response/",
                 data:datum,
                 success:function(data){
                   alert('successfully: The Product Has Been'+data.status)
                 },
                 error:function(err){
                     alert('error :'+err);
                 }
                 
             });
        }
        
    })
</script>
{% endblock formadjust %}

product/templates/main/pack/requested.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
{{block.super}}

<div class="single-product-area detail-section section-padding-100 clearfix">
    <div class="container-fluid">
       
        <div id="breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    
                    <li  style="padding:10px; "><a href="{% url 'accounts:my-pack' %}" class="active" >All Orders |</a> </li>
                    <li style="padding:10px;"><a href="{% url 'accounts:my-pack-requested' %}" style="color: rgb(243, 162, 55);">Requested orders |</a></li>
                    <li style="padding:10px;" ><a href="{% url 'accounts:my-pack-shipped' %}">Shiped orders |</a></li>
                    <li style="padding:10px;"><a href="{% url 'accounts:my-pack-delivered' %}">Delivered orders |</a></li>
                    <li style="padding:10px;"><a href="{% url 'accounts:my-pack-returned' %}">Returned orders</a></li>
                </ul>
            </div>
        </div>
        
       
        {% for obj in user.salerecord_set.all %}
        {% if obj.paid %}
        {% if obj.status == "requested" %}
        <div id="breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    
                    <li class="active">{{obj.product.name| title}}</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-7">
                <div class="single_product_thumb">
                    <div id="product_details_slider" class="carousel slide" data-ride="carousel">
                      
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                    <img class="gallery_img d-block w-100" style="height: 300px;" src="{{obj.product.image.url}}" alt="{{obj.product.name}}">
                               
                            </div>
                          
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-5">
                <div class="single_product_desc">
                    <!-- Product Meta Data -->
                    <div class="product-meta-data">
                        <div class="line"></div>
                        
                            <h3 style="display: inline;">Package Number: {{obj.package_number}}</h3>
                       
                        <div class="line"></div>
                        <h3 class="">&#8358;{{obj.price}} </h3>
                        <h5 class="product-price">Quantity Requested: {{obj.quantity}} </h5>
                        <h5 class="product-price">Size Requested: {{obj.size}} </h5>
                        <h5 class="product-price">Color Requested: {{obj.color}} </h5>
                        
                      
                        <!-- Avaiable -->
                        <p class="avaibility"><a href="/{{obj.product.company.slug}}">Sold by : {{obj.product.company.name}}</a></p><br/>
                        <h6 class="text-muted">Requested On: {{obj.package_time}} </h6>
                        {% if obj.status == 'delivered' %}
                        <h6 class="text-muted">Delivered On: {{obj.delivery_time}} </h6>
                        {% elif obj.status == 'returned' %}
                        <h6 class="text-muted">Returned On: {{obj.returned_time}} </h6>
                        {% elif obj.status == 'shipped' %}
                        <h6 class="text-muted">Shipped On: {{obj.shipped_time}} </h6>
                        {% endif %}
                    </div>


                
                    
      
                    
                       
                        <form class="cart clearfix cart-form" method="post" action="{% url 'add_cart' %}" >{% csrf_token %}
                           {% if obj.status == 'returned' %}
                            <button class="primary-btn add-to-cart " onclick="event.preventDefault()">Status: {{obj.status| title}} </button>
  
                            {% elif obj.status == 'shipped' %}
                            <button class="primary-btn add-to-cart accept-btn">Accept It</button>
                            <input type="hidden" id="saleId" value="{{obj.id}}" />
                            <button class="main-btn  add-to-cart return-btn" >Returned</button>
                            {% endif %}
                        </form>
                        
                    
                       <p>Your order would be delivered within five (5) working days</p>

                      
                    
                    

                </div>
            </div>
        </div>
        {% endif %}
        {% endif %}
        {% endfor %}
        
       
      
    </div>
    </div>

    {% endblock content %}
    {% block formadjust %}
<script type="text/javascript">
    $('document').ready(function(){
        var saleId=$("#saleId").val();
        $('.cart-form .accept-btn').on("click", function(event){
            event.preventDefault();
            datum={
                "status":"accepted",
                "sale_id":saleId,
                "csrfmiddlewaretoken":"{{csrf_token}}"
            }
            myRespond(datum);
        });
        $('.cart-form .return-btn').on("click", function(event){
            event.preventDefault();
            datum={
                "status":"rejected",
                "sale_id":saleId,
                "csrfmiddlewaretoken":"{{csrf_token}}"
            }
            myRespond(datum);
        });
        function myRespond(datum){
          
            $.ajax({
                 type:'POST',
                 url:"/record/customer-response/",
                 data:datum,
                 success:function(data){
                   alert('successfully: The Product Has Been'+data.status)
                 },
                 error:function(err){
                     alert('error :'+err);
                 }
                 
             });
        }
        
    })
</script>
{% endblock formadjust %}