accounts/urls.py
from django.urls import path, include
from django.views.generic import TemplateView


from django.views.generic import TemplateView
from .views import SaleRecordApi,PackApi,DeliveryResponseApi,CustomerResponseApi, MyPack

app_name='accounts'


urlpatterns = [
   
    path('sale/', SaleRecordApi.as_view(), name='sale-record'),
    path('pack/', PackApi.as_view(), name='pack-record'),
    path('delivery-company/', DeliveryResponseApi.as_view(), name='delivery-company'),
    path('customer-response/', CustomerResponseApi.as_view(), name='user-response'),
    path('my-pack/', MyPack.as_view(template_name="main/pack/customer_response.html"), name='my-pack'),
    path('my-pack/shipped/', MyPack.as_view(template_name="main/pack/shipped.html"), name='my-pack-shipped'),
    path('my-pack/delivered/', MyPack.as_view(template_name="main/pack/delivered.html"), name='my-pack-delivered'),
    path('my-pack/requested/', MyPack.as_view(template_name="main/pack/requested.html"), name='my-pack-requested'),
    path('my-pack/returned/', MyPack.as_view(template_name="main/pack/returned.html"), name='my-pack-returned'),
    
]

cart/urls.py
from django.urls import path, include
from django.views.generic import TemplateView


from .views import CartList,CartUpdateToggle,pay_now,DeliveryTypeApi

app_name='cart'


urlpatterns = [
   
    path('', CartList.as_view(), name='cart'),
    path('update/', CartUpdateToggle.as_view(), name='update'),
    path('delivery-type/', DeliveryTypeApi.as_view(), name='update'),
    path('pay/', pay_now, name='pay'),

    
]

company/urls.py
from django.urls import path


from django.views.generic import TemplateView
from .views import (
CompanyProfile,
companycreate_view,
companyupdate_view,
Companies,
ApiCompanyList,
ApiCompanyDetail,
companyaccount,
companybankaccount
# productscreate_view
	)
app_name="company"
urlpatterns = [
	path('companies/',Companies.as_view(), name='list'),
	path('<slug>/',CompanyProfile.as_view(), name='detail'),
	path('<slug>/account/',companyaccount, name='detail-account'),
	path('company/bank-info/',companybankaccount, name='bank-detail'),
	path('<slug>/delivered/',CompanyProfile.as_view(template_name="main/company/delivered.html"), name='detail-delivered'),
	path('<slug>/returned/',CompanyProfile.as_view(template_name="main/company/returned.html"), name='detail-returned'),
	path('<slug>/requested/',CompanyProfile.as_view(template_name="main/company/requested.html"), name='detail-requested'),
	path('<slug>/shiped/',CompanyProfile.as_view(template_name="main/company/shiped.html"), name='detail-shiped'),
	path('create/form/',companycreate_view, name='create'),
	path('update/form/',companyupdate_view, name='update'),
    path('api/list/',ApiCompanyList.as_view(), name='api-list'),
	path('api/<slug>/',ApiCompanyDetail.as_view(), name='api-detail'),
   
]

delivery/urls.py
from django.urls import path



from django.views.generic import TemplateView
from .views import (
	checkout_view,
	checkout,
	ApiUserList,
	ApiDeliveryDetail
	
	)


app_name="delivery"
urlpatterns = [
    path('', checkout_view, name='delivery-info'),
	path('pack/checkout/', checkout, name='checkout'),
	path('api/', ApiUserList.as_view(), name='api'),
	path('api/me/', ApiDeliveryDetail.as_view(), name='api-detail'),


	
    
   
]

ojaale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns


from django.views.generic import TemplateView
from cart.views import CartToggle
from user_profile.views import RegisterView
from product.views import index
from major.views import Search
from referal.views import registerview


from rest_framework import routers

router = routers.DefaultRouter()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products')),
    path('delivery/', include('delivery.urls', namespace='delivery')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('record/', include('accounts.urls', namespace='record')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('', include('company.urls', namespace='company')),
    path('referral/', include('referal.urls', namespace='referral')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('profile/', include('user_profile.urls', namespace='profile')),
    path('cart/add_cart/', CartToggle.as_view(), name='add_cart'),
    path('account/register/', RegisterView.as_view(), name='register'),
    path('store/search/', Search.as_view(), name='search'),
    path('policies/learn-more/', TemplateView.as_view(template_name="main/policies.html"), name='learn-more'),
    path('test/test/', TemplateView.as_view(template_name="main/emails/advert-add-product.html"), name='learn-more'),
   path('gift-giving/now/', TemplateView.as_view(template_name="main/squeeze/index.html"), name='learn-more'),
   
    
    path('',index , name='home'),
    
    path('account/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += router.urls

product/urls.py
from django.urls import path

from rest_framework import routers

router = routers.DefaultRouter()


from .views import (
	ProductsList,
	productdetail,
	productcreate_view,
	productupdate_view,
	ApiProductList,
	ApiProductDetail
    

	)
app_name="products"
urlpatterns = [
    path('', ProductsList.as_view(), name='list'),
	
	path('<slug>/',productdetail, name='detail'),
	path ('create/form/', productcreate_view, name='create'),
	path ('<slug>/update/', productupdate_view, name='update'),


	path('api/list/', ApiProductList.as_view(), name='api-list'),
	path('api/detail/<pk>/', ApiProductDetail.as_view(), name='api-detail'),
	#ProductsDetail.as_view(), name='detail'),
    
   
]
urlpatterns += router.urls

user_profile/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from .views import mynotifications,profileupdate_view

app_name='profile'


urlpatterns = [
    path('email-test/',TemplateView.as_view(template_name='main/emails/email1/welcome-info-email.html'), name="update"),
   path('update/',profileupdate_view, name="update"),
    path('notifications/', mynotifications, name='notifications'),
    #  path(
    #     'change-password/',
    #     auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html'),
    # ),
    # path(
    #     'password_reset/',
    #     auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
    # ),
    # path(
    #     'change-password/',
    #     auth_views.PasswordResetConfirmView.as_view(template_name='change-password.html'),
    # ),
    
    
    
    
    
]

product/views.py
# API
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from .serializers import ProductSerializers


#PYTHON

from itertools import chain

from  django.db.models import Count

from django.core.paginator import Paginator

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from urllib.parse import quote

from django.urls import reverse

from django.db.models import Q
from django.http import HttpResponseRedirect,Http404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import View, ListView, DetailView
from django.utils import timezone

from referal.models import Referral
from .models import Products, ProductPriceRanges
from reviews.forms import ReviewForm
from reviews.models import Review
from cart.models import Cart
from .forms import ProductForm
from company.models import Company
from accounts.models import SaleRecord,Pack
from django.template import loader
from django.core.mail import send_mail
from ojaale.settings import EMAIL_HOST_USER

from django import template
register = template.Library()

# Create your views here.


User=get_user_model()
def index(request):
	template_name="main/index_try.html"
	shops=Company.objects.all()
	products=Products.objects.all()
	picked_products=Products.objects.all().order_by("timestamp")
	fashion_products=Products.objects.filter(category="fashion")
	furniture_products=Products.objects.filter(category="furnitures and woodwork")
	electronic_products=Products.objects.filter(category="electronics and phones")
	livestock_products=Products.objects.filter(category="pets and livestocks")
	home_products=Products.objects.filter(category="home and kitchen")
	automobile_products=Products.objects.filter(category="automibiles and industrial machines")
	health_products=Products.objects.filter(category="health and beauty")
	cart_=None
	if request.user.is_authenticated:
		request_customer=request.user
		check_referred=Referral.objects.filter(customers=request_customer)
		# if not check_referred:
		# 	referral_link=request.COOKIES['referral_link']
		# 	referrer,in_customer = Referral.objects.toggle_customer(request_customer, referral_link)
	
	

	if request.user.is_authenticated:
		cart_=get_object_or_404(Cart, user=request.user)
		sales=SaleRecord.objects.filter(user=request.user)
	context={
		"products":products,
		"shops":shops,
		"picked_products":picked_products,
		"fashion_products":fashion_products,
		"electronic_products":electronic_products,
		"livestock_products":livestock_products,
		"home_products":home_products,
		"automobile_products":automobile_products,
		"health_products":health_products,
		"furniture_products":furniture_products,
		'carts':cart_

	}
	return render(request, template_name, context)

class ProductsList(ListView):
	queryset=Products.objects.all()
	template_name='main/product/list.html'
	# for query in queryset:
	# 	reviews=[x.rating for x in Review.objects.filter(content_type=query.get_content_type)]
		
	
	# for review in reviews:
	# 	print(review)

	def get_context_data(self, *args, **kwargs):
		context=super(ProductsList,self).get_context_data(*args, **kwargs)
		if self.request.user.is_authenticated:
			cart_=get_object_or_404(Cart, user=self.request.user)
			context['carts']=cart_

		return context
	



def productdetail(request, slug=None):
	instance = get_object_or_404(Products, slug=slug)
	product_ranges=ProductPriceRanges.objects.filter(product=instance)
	reviews=Review.objects.filter_by_instance(instance)
	prev_review=None
	allow_to_review=None
	if request.user.is_authenticated:
		prev_review=reviews.filter(user=request.user)
		allow_to_review=Pack.objects.filter(contents__product=instance, user=request.user)
		
	share_string= quote(instance.description)
	
	initial_data={
		"content_type":instance.get_content_type,
		"object_id":instance.id
	}
	# if request.method == "POST":
	# 	if prev_review:
	# 		form=ReviewForm(request.POST or None)
	# 		if form.is_valid():
	# 			content_data=form.cleaned_data.get("content")
	# 			rating=request.POST.get('rating')
	# 			prev_review.content=content_data
	# 			prev_review.rating=rating
	# 			prev_review.save()
	# 	else:
	form=ReviewForm(request.POST or None, initial=initial_data)
	if form.is_valid():
		c_type=form.cleaned_data.get("content_type")
		content_type=ContentType.objects.get(model=c_type)
		obj_id=form.cleaned_data.get("object_id")
		content_data=form.cleaned_data.get("content")
		rating=request.POST.get('rating')
		parent_obj=None
		try:
			parent_id=int(request.POST.get('parent_id'))
		except:
			parent_id=None
		if parent_id:
			parent_qs=Review.objects.filter(id=parent_id)
			if parent_qs.exists():
				parent_obj=parent_qs.first()
				print(parent_obj)
		new_review, created=Review.objects.get_or_create(
			user=request.user,
			content_type=content_type,
			object_id=obj_id,
			content=content_data,
			parent=parent_obj,
			rating=rating
			)
		reviews_count=reviews.count()
		rating=[x.rating for x in reviews]
		
		sumrating=sum(rating)
		if reviews_count >0:
			meanrating=round((sumrating/(reviews_count)),2)
			instance.rating=meanrating
			instance.save()
		product_company=instance.company
		company_products=Products.objects.filter(company=product_company)
		
		list_products_rating=[prod.rating for prod in company_products]
		
		product_company.rating=(sum(list_products_rating)/len(list_products_rating))
		product_company.save()
		

		return HttpResponseRedirect(new_review.content_object.get_absolute_url())
	
	
	

	
	
	context={
		'object':instance,
		'reviews':reviews,
		'review_form':form,
		"allow_to_review":allow_to_review,
		'product_ranges':product_ranges
		# 'needed_record':needed_record
		# 'product_name':instance.name,
		# 'in_cart':in_cart
		
	}
	template='main/product/detail_test.html'
	return render(request,'main/product/detail.html',context)

@login_required()
def productcreate_view(request):
	if request.user.company:
		sub_category=request.POST.get("sub_category")
		form = ProductForm(request.POST,request.FILES)
		cat_filter=request.user.company.product_cat
		print(form.is_valid())
		if form.is_valid():
			instance=form.save(commit=False)
			print("got here")
			instance.sub_category=sub_category
			instance.category=request.user.company.product_cat
			instance.company=request.user.company
			discount=100-(((instance.price)/(instance.discounted_from))*100)
			instance.discount=discount
			print("got here")
			instance.save()
			messages.success(request, "Successfully Created")
			html_message = loader.render_to_string(
                            'main/emails/advert-add-product.html',
                            {
                                'product':instance, 
                            }
                        )
			all_users=User.objects.filter(cart__advert_email_unsubscribe=False)
			email_list=[x.email for x in all_users]
			#send_mail(f"Waw!!! A New Products Has Been Added To {instance.company.name}. Check It Out Now!!!","message",EMAIL_HOST_USER,email_list,fail_silently=True,html_message=html_message)
			return HttpResponseRedirect(f'/products/{instance.slug}')
    
		context={"form":form,"title":"Add Products To Store","button":"Add","cat_filter":cat_filter}
		template_name='main/product/form.html'
		return render(request, template_name,context)
	else:
		return HttpResponseRedirect("/create/form/")
@login_required()
def productupdate_view(request, slug):
	obj=get_object_or_404(Products, slug=slug )
	sub_category=request.POST.get("sub_category")
	if request.user.company == obj.company:
		cat_filter=request.user.company.product_cat
		if request.method=='POST':
			form = ProductForm(request.POST, request.FILES, instance=obj)
			if form.is_valid():
				instance=form.save(commit=False)
				instance.sub_category=sub_category
				instance.category=request.user.company.product_cat
				instance.company=request.user.company
				discount=100-(((instance.price)/(instance.discounted_from))*100)
				instance.discount=discount
				instance.save()
				messages.success(request, "Successfully Created")
				return HttpResponseRedirect(f'/products/{instance.slug}')
		else:
			form=ProductForm(instance=obj)
		context={"form":form,"title":"Update Product ","button":"Update","cat_filter":cat_filter}
		template_name='main/product/form.html'
		return render(request, template_name,context)
	else:
		return HttpResponseRedirect("/create/form/")

@register.filter
def not_seen(things):
    return things.filter(seen=False)

#Api Views-------------------------------------------------------------------------------------------------

class ApiProductList(APIView):
    """
    List all products, or create a new product.
    """
    def get(self, request, format=None):
        products = Products.objects.all()
        serializer = ProductSerializers(products, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = ProductSerializers(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ApiProductDetail(APIView):
    """
    Retrieve, update or delete a Product instance.
    """
    def get_object(self, pk):
        try:
            return Products.objects.get(pk=pk)
        except Products.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        product = self.get_object(pk)
        serializer = ProductSerializers(product)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        product = self.get_object(pk)
        serializer = ProductSerializer(product, data=request.data)

product/templates/main/footer.html
<!-- ##### Footer Area Start ##### -->
<footer class="footer_area clearfix">
    <div class="container">
        <div class="row align-items-center">
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-4">
                <div class="single_widget_area">
                    <!-- Logo -->
                    <div class="footer-logo mr-50">
                        <a href="index.html"><img src="img/core-img/logo2.png" alt=""></a>
                    </div>
                    <!-- Copywrite Text -->
                    <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy; All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by  <a href="https://colorlib.com" target="_blank">Taimtom Digitals</a> and <a href="https://colorlib.com" target="_blank"> Colorlib</a></p>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-8">
                <div class="single_widget_area">
                    <!-- Footer Menu -->
                    <div class="footer_menu">
                        <nav class="navbar navbar-expand-lg justify-content-end">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                            <div class="collapse navbar-collapse" id="footerNavContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="/">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'company:list' %}">Shops</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'products:list' %}">Products</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'cart:cart' %}">Cart</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'delivery:delivery-info' %}">Checkout</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

product/templates/main/header-mini.html
 
        
{% load static %}
        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="{% url 'home' %}"><img style="width:60%;" src="{% static 'img/core-img/mainlogo.jpg' %}"  alt=""></a>
            </div>
            <!-- Navbar Toggler -->
        
            
            
            <!-- <div class="amado-navbar-toggler">
                
                <span></span><span></span><span></span>
            </div> -->
            <!-- Mobile nav toggle-->
            <div class="mobile-nav-list">
                <ul>
                  
                    
                   
                    <li ><a href="{% url 'company:list' %}">
                        <img class="head-icon" src="{% static 'img/core-img/shop.png' %}"  />
                        <!-- <div class="header-text">Shops/offices</div> -->
                    </a></li>
                    <!-- <li><a href="{% url 'delivery:checkout' %}">Checkout</a></li> -->
                     <!-- Cart -->
                     {% if user.is_authenticated %}
            <li class="header-cart dropdown default-dropdown" style="margin-left: -12px;">
                <a class="" data-toggle="dropdown" aria-expanded="true">
                    <div class="header-btns-icon">
                        <!-- <i class="fa fa-shopping-cart"></i> -->
                        <!-- <div class="header-text">
                            <img src="{% static 'img/core-img/cart.png' %}"  alt="">
                        Cart
                        </div> -->
                        
                        <img class="head-icon" src="{% static 'img/core-img/carts.png' %}" alt="">
                        <span class="qty" id="cartTotal"> {{request.user.cart.content.count}}</span>
                    </div>
                    
                               
                    
                </a>
                <div class="custom-menu">
                    <div id="shopping-cart">
                        <div class="shopping-cart-list header-cart-list">
                            
                            {% for product in request.user.cart.content.all %}
                            <div class="product product-widget">
                                <div class="product-thumb">
                                    <img src="{{product.product.image.url}}" alt="">
                                </div>
                                <div class="product-body">
                                    <h3 class="product-price">&#8358;{{product.product.price}} <span class="qty">x{{product.quantity}}</span></h3>
                                    <h2 class="product-name"><a href="{{product.product.get_absolute_url}}">{{product.product.name}}</a></h2>
                                </div>
                                <form class="cart clearfix" method="post" action="{% url 'add_cart' %}">{% csrf_token %}
                                    <input type="hidden" name="sale_id" value="{{product.id}}" />
                                    <button class="cancel-btn"><i class="fa fa-trash"></i></button>
                                    
                                </form>
                                
                            </div>
                            {% empty %}
                            <h3 class="text-muted"> No Item In Cart</h3>
                            {% endfor %}
                            
                          
                        </div>
                        <div class="shopping-cart-btns">
                            <a href="{% url 'cart:cart' %}"><button class="main-btn" >View Cart</button></a>
                            <a href="{% url 'delivery:delivery-info' %}"> <button class="primary-btn">Checkout </button></a>
                        </div>
                    </div>
                </div>
            </li>
            {% endif %}
            <!-- /Cart -->
                    <!-- <li><a href="{% url 'cart:cart' %}" class="cart-nav"><img src="{% static 'img/core-img/cart.png' %}" alt=""> <span class="qty"></span>Cart <span>({% for cart in user.cart_set.all %} {{cart.products.count}} {% endfor %})</span></a></li> -->
                   
                    <li class="header-cart dropdown default-dropdown" >
                        <a class="" data-toggle="dropdown" aria-expanded="true">
                            <div class="header-btns-icon">
                                <!-- <i class="fa fa-shopping-cart"></i> -->
                                
                              
                                
                                 <!-- <div class="header-text">Search <img  src="{% static 'img/core-img/search.png' %}" alt=""></div> -->
                                <img class="head-icon" src="{% static 'img/core-img/search1.png' %}" alt="">
                            </div>
                            
                        </a>
                        <div class="custom-menu">
                            <div id="shopping-cart">
                                <div class="shopping-cart-list">
                            <form method="GET" action="{% url 'search' %}">
                           
                                
                                
                                    
                                    
                                        
                                       
                                        <div class="input-group">
                                            <input size="25" style="overflow: hidden; border-radius: 5px;" class="" type="text" name="search">
                                            <button class="main-btn icon-btn "><i class="fa fa-search"></i></button>
                                       </div>
                                       
                                   
                                    
                                  
                              
                                
                                </form>
                            </div>
                        </div>
                        </div>
                    </li>
                    {% if user.is_authenticated %}
                    <li class=" dropdown default-dropdown " >
                        <a class="" data-toggle="dropdown" aria-expanded="true">
                            <div class="header-btns-icon">
                                <!-- <i class="fa fa-shopping-cart"></i> -->
                                <!-- <div class="header-text" style="font-weight: bold;">
                                    <img width="25px" src="{% static 'img/core-img/users.png' %}"  alt="">
                                    
                                </div> -->
                                <!-- {{user.username|title}} -->
                                <img class="head-icon" src="{% static 'img/core-img/users.png' %}" alt="">
                                <!-- <i class="fa fa-caret-down" aria-hidden="true"></i> -->
                               
                            </div>
                            
                        </a>
                        <div class="custom-menu" style="width: min-content;">
                            <div id="shopping-cart">
                                <div class="shopping-cart-list">
                                    <div class="product-body">
                                        <h3 class="product-price">{% if user.company %}<a href="{{user.company.get_company_url}}">{{user.company.name}}</a>{% else %}<a href="{% url 'company:create' %}"> Sell Products</a>{% endif %}</h3>
                                                          {% if user.company %}              <h3 class="product-name"><a href="{% url 'company:update' %}">Update Company's Info</a></h3>
                                                      <h4 class="product-name"><a href="{% url 'products:create' %}">Add Goods To Store</a></h4>
                           
                           {% endif %}              
                           {% if user.company %}{% if not user.company.bankaccountdetail %}<h4 class="product-name"><a href="{% url 'company:bank-detail' %}">Add Bank Account</a></h4>{% endif %}{% endif %}
                           <h2 class="product-name"><a href="{% url 'referral:create' %}">Invite People</a></h2>
                           <h3><a href="{% url 'accounts:my-pack' %}">Order Info</a></h3>
                           <h3><a href="{% url 'profile:notifications' %}">Notifications({{user.notification_set.all.count}})</a></h3>
                                                 <h3 ><a href="{% url 'logout' %}">Log Out</a></h3>          </div>
                            </div>
                        </div>
                    
                    </div>
                    
                   </li>
                   {% else %}
                   <li class="header-cart">
                                
                    <a href="{% url 'login' %}" > 
                        
                        <!-- <div class="header-btns-icon header-text">
                            Favourite<img  src="{% static 'img/core-img/favorites.png' %}" alt="">
                            
                        </div> -->
                        <img class="head-icon" style="width: 35px;" src="{% static 'img/core-img/loginimg.png' %}" alt="Login">
                    </a>
                    
                
            </li>
  {% endif %}
                  <li class="nav-toggle" style="margin-left: -2px;" id="navbar-toggler">
                        <button class="nav-toggle-btn" style="background-color: white; border: none; width: 4px; "><img class="head-icon" src="{% static 'img/core-img/dot.png' %}"></button>
                    </li>
                   
                </ul>
            </div>
           
           
        </div>

product/templates/main/policies.html
{% extends 'main/base_test.html' %}
{% block content %}
{{block.super}}

<p>
    it has to be  done within 7 days after request as soon as the buyer indicates the item has been recieved your ojaa.me account will be credited and disbusment will be made to your band account within 24 hours.
</P>
<p>
    The unmonitored plan allows you to collect the money for purchase items within 24 hours after purchase but a caution sign will be placed on the web site and each product as unmonitored thus ojaa.me is not liable to any problem as a result of such transaction.
</p>
{% endblock content %}