cart/urls.py
from django.urls import path, include
from django.views.generic import TemplateView


from .views import CartList,CartUpdateToggle,pay_now,DeliveryTypeApi

app_name='cart'


urlpatterns = [
   
    path('', CartList.as_view(), name='cart'),
    path('update/', CartUpdateToggle.as_view(), name='update'),
    path('delivery-type/', DeliveryTypeApi.as_view(), name='update'),
    path('pay/', pay_now, name='pay'),

    
]

company/urls.py
from django.urls import path


from django.views.generic import TemplateView
from .views import (
CompanyProfile,
companycreate_view,
companyupdate_view,
Companies,
ApiCompanyList,
ApiCompanyDetail,
companyaccount,
companybankaccount
# productscreate_view
	)
app_name="company"
urlpatterns = [
	path('companies/',Companies.as_view(), name='list'),
	path('<slug>/',CompanyProfile.as_view(), name='detail'),
	path('<slug>/account/',companyaccount, name='detail-account'),
	path('company/bank-info/',companybankaccount, name='bank-detail'),
	path('<slug>/delivered/',CompanyProfile.as_view(template_name="main/company/delivered.html"), name='detail-delivered'),
	path('<slug>/returned/',CompanyProfile.as_view(template_name="main/company/returned.html"), name='detail-returned'),
	path('<slug>/requested/',CompanyProfile.as_view(template_name="main/company/requested.html"), name='detail-requested'),
	path('<slug>/shiped/',CompanyProfile.as_view(template_name="main/company/shiped.html"), name='detail-shiped'),
	path('create/form/',companycreate_view, name='create'),
	path('update/form/',companyupdate_view, name='update'),
    path('api/list/',ApiCompanyList.as_view(), name='api-list'),
	path('api/<slug>/',ApiCompanyDetail.as_view(), name='api-detail'),
   
]

delivery/urls.py
from django.urls import path



from django.views.generic import TemplateView
from .views import (
	checkout_view,
	checkout,
	ApiUserList,
	ApiDeliveryDetail
	
	)


app_name="delivery"
urlpatterns = [
    path('', checkout_view, name='delivery-info'),
	path('pack/checkout/', checkout, name='checkout'),
	path('api/', ApiUserList.as_view(), name='api'),
	path('api/me/', ApiDeliveryDetail.as_view(), name='api-detail'),


	
    
   
]

ojaale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns


from django.views.generic import TemplateView
from cart.views import CartToggle
from user_profile.views import RegisterView
from product.views import index
from major.views import Search
from referal.views import registerview


from rest_framework import routers

router = routers.DefaultRouter()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products')),
    path('delivery/', include('delivery.urls', namespace='delivery')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('record/', include('accounts.urls', namespace='record')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('', include('company.urls', namespace='company')),
    path('referral/', include('referal.urls', namespace='referral')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('profile/', include('user_profile.urls', namespace='profile')),
    path('cart/add_cart/', CartToggle.as_view(), name='add_cart'),
    path('account/register/', RegisterView.as_view(), name='register'),
    path('store/search/', Search.as_view(), name='search'),
    path('policies/learn-more/', TemplateView.as_view(template_name="main/policies.html"), name='learn-more'),
    path('test/test/', TemplateView.as_view(template_name="main/emails/advert-add-product.html"), name='learn-more'),
   path('gift-giving/now/', TemplateView.as_view(template_name="main/squeeze/index.html"), name='learn-more'),
   
    
    path('',index , name='home'),
    
    path('account/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += router.urls

product/urls.py
from django.urls import path

from rest_framework import routers

router = routers.DefaultRouter()


from .views import (
	ProductsList,
	productdetail,
	productcreate_view,
	productupdate_view,
	ApiProductList,
	ApiProductDetail
    

	)
app_name="products"
urlpatterns = [
    path('', ProductsList.as_view(), name='list'),
	
	path('<slug>/',productdetail, name='detail'),
	path ('create/form/', productcreate_view, name='create'),
	path ('<slug>/update/', productupdate_view, name='update'),


	path('api/list/', ApiProductList.as_view(), name='api-list'),
	path('api/detail/<pk>/', ApiProductDetail.as_view(), name='api-detail'),
	#ProductsDetail.as_view(), name='detail'),
    
   
]
urlpatterns += router.urls

referal/urls.py
from django.urls import path

from .views import (
	Dashboard,
	SendReferralEmail,
    ReferralCreate,
	registerview,
	ReferralDashboardViev,
	withdrawal,
	ApiReferralDetail
	
    

	)
app_name="referral"
urlpatterns = [
	
	path('<username>/',Dashboard.as_view(), name='detail'),
	path ('create/form/', ReferralCreate.as_view(), name='create'),
	path ('email/send/', SendReferralEmail.as_view(), name='send-email'),
	path ('<referral_link>/register/', registerview, name='register'),
	path ('s/api/', ReferralDashboardViev.as_view()),
	path ('s/api/me/', ApiReferralDetail.as_view()),
	#path ('sale/api/', SaleRecordAPIViewDashboard.as_view()),
	path ('user/withdraw/', withdrawal, name="withdraw")
	 
]

product/models.py
from django.db import models
# from django.contrib.postgres.search import SearchVector, SearchQuery
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

from .utils import unique_slug_generator
from company.models import Company

from reviews.models import Review

User=settings.AUTH_USER_MODEL



class ProductQuerySet(models.QuerySet):
  def search(self,query=None):
    qs=self
    if query is not None:
      

      look_up=Q()
      for word in query.split():
        look_up &= (Q(name__icontains=query)|
          Q(brand__icontains=query)|
          Q(color__icontains=query)|
          Q(sub_category__icontains=query)|
          Q(category__iexact=query))


      qs=qs.filter(look_up).distinct()
    return qs
  def cat_search(self,category_search=None):
    qs=self
    if category_search is not None:
      look_up=(Q(category__iexact=category_search)|
      Q(name__icontains=category_search)|
      Q(sub_category__iexact=category_search)|
      Q(description__iexact=category_search))
      qs=qs.filter(look_up).distinct()
    return qs

class ProductManager(models.Manager):
	def get_queryset(self):
		return ProductQuerySet(self.model, using=self._db)

	def search(self,query=None):
		return self.get_queryset().search(query)
  # def cat_search(self,query=None):
	# 	return self.get_queryset().search(category_search)
class Products(models.Model):
    company=models.ForeignKey(Company, on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    category=models.TextField()
    sub_category=models.CharField(max_length=100, null=True,blank=True )
    price=models.IntegerField()
    discount=models.IntegerField(default=0)
    discounted_from=models.IntegerField(null=True,blank=True)
    status=models.CharField(max_length=30, default="New" )
    availability=models.IntegerField(default=0)
    brand=models.CharField(max_length=100)
    size=models.CharField(max_length=100, null=True, blank=True)
    description=models.TextField()
    color=models.CharField(max_length=30,null=True, blank=True)
    rating=models.FloatField(default=0)
    image=models.FileField(upload_to='product/image')
    timestamp=models.DateTimeField(auto_now_add=True)
    slug=models.SlugField(null=True, blank=True)

    objects=ProductManager()

    class Meta:
      ordering=["-timestamp"]


    def __str__(self):
      return self.name
    
    def get_absolute_url(self):
      return reverse("products:detail", kwargs={'slug':self.slug})
    
    @property
    def get_content_type(self):
      instance=self
      content_type=ContentType.objects.get_for_model(instance.__class__)
      return content_type


class ProductImages(models.Model):
  product=models.ForeignKey(Products, on_delete=models.CASCADE)
  image=models.ImageField(upload_to='product/images')
  alt=models.CharField(max_length=200, null=True, blank=True)
  def __str__(self):
      return str(self.product.name) + str(self.id)

class ProductPriceRanges(models.Model):
  product=models.ForeignKey(Products, on_delete=models.CASCADE)
  start_quantity=models.IntegerField()
  stop_quantity=models.IntegerField()
  price=models.DecimalField(max_digits=20, decimal_places=2)

  def __str__(self):
      return str(self.product.name) + str(self.id)

class ProductVariant(models.Model):
  product=models.ForeignKey(Products, on_delete=models.CASCADE)
  
  def __str__(self):
      return str(self.product.name) + str(self.id)

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
	instance.name = instance.name.capitalize()
	if not instance.slug:
		instance.slug =unique_slug_generator(instance)
pre_save.connect(rl_pre_save_receiver, sender=Products)

company/views.py
# API
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from .serializers import  CompanySerializers

#python


from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import View, ListView, DetailView, CreateView
from .models import Company, BankAccountDetail
from product.models import Products
from django.http import HttpResponseRedirect,Http404
from django.contrib import messages
from .forms import CompanyForm,CompanyAccountForm#, ProductForm
from accounts.models import SaleRecord
# Create your views here.

class Companies(ListView):
   template_name='main/company/companies.html'
   queryset=Company.objects.all()

class CompanyProfile(DetailView):
   def get_object(self):
       slug= self.kwargs.get("slug")
       if slug is None:
           raise Http404
       return get_object_or_404(Company,slug__iexact=slug)
   template_name="main/company/profile.html"
   def get_context_data(self, *args, **kwargs):
       context=super(CompanyProfile,self).get_context_data(*args, **kwargs)
       company=self.get_object()
       sale_record=SaleRecord.objects.filter(product__company=company)
       delivered_record=SaleRecord.objects.filter(product__company=company, status__iexact="delivered", paid=True)
       requested_record=SaleRecord.objects.filter(product__company=company, paid=True)
       returned_record=SaleRecord.objects.filter(product__company=company, status__iexact="returned", paid=True)
       top_rated=Company.objects.order_by("rating")
       context={
           "object":company,
           "top_rated":top_rated,
           "delivered":delivered_record,
           "requested":requested_record,
           "returned":returned_record,
       }
       return context
@login_required()
def companyaccount(request,slug=None):
    instance=get_object_or_404(Company, slug=slug)
    mysales=SaleRecord.objects.filter(paid=True, product__company=instance)
    customers=[sale.user for sale in mysales]
    if request.user != instance.owner:
        return HttpResponseRedirect(f"/{slug}")
    
    context={
       "account":instance.account,
       "object":instance,
       "customers":set(customers)
       
       }
    template_name='main/company/profile-acc.html'
   
        
    
    return render(request, template_name,context)
@login_required()
def companybankaccount(request):
    obj=get_object_or_404(Company, owner=request.user)
    if not obj:
        return HttpResponseRedirect("/create/form/")
    else:
        form = CompanyAccountForm(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.user=obj
            instance.save()
            messages.success(request, "Successfully Created")
            return HttpResponseRedirect('/products/create/form/')  
        context={
            "object":obj,
            "form":form,
            "title":"Add Bank Account",
            "button":"Add"
        }
    template_name='main/company/form.html'
    return render(request, template_name,context)
@login_required()
def companycreate_view(request):
  company=Company.objects.filter(owner=request.user)
  if company:
    return HttpResponseRedirect("/update/form/")
  else:
    form = CompanyForm(request.POST, request.FILES)
    if form.is_valid():
        instance=form.save(commit=False)
        instance.owner=request.user
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect('/products/create/form/')
        
    if form.errors:
        print(form.errors)
        context={"form":form}
    context={
       "form":form,
       "title":"Create Your Online Store",
       "button":"Creaate Store"
       }
    template_name='main/company/form.html'
   
        
    
    return render(request, template_name,context)
@login_required()
def companyupdate_view(request):
  company=Company.objects.filter(owner=request.user)
  if not company:
    return HttpResponseRedirect("/create/form/")
  else:
    obj=get_object_or_404(Company, owner=request.user)
    if request.method=='POST':
      form = CompanyForm(request.POST, request.FILES, instance=obj)
      if form.is_valid():
        instance=form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_company_url())
    else:
      form=CompanyForm(instance=obj)
    context={
       "form":form,
       "title":"Update Your Online Store",
       "button":"Update Store"
       }
    template_name='main/company/form.html'
   
        
    
    return render(request, template_name,context)
    
# def productscreate_view(request, slug=None):
#     form = ProductForm(request.POST)
#     instances=get_object_or_404(Company,slug=slug)
#     if form.is_valid():
#         instance=form.save(commit=False)
#         instance.company=instances
#         print(instance.company)
#         instance.save()
#         messages.success(request, "Successfully Created")
#         return HttpResponseRedirect(f'/company/{instances.slug}')
        
#     if form.errors:
#         print(form.errors)
#         context={"form":form}
#     context={
#        "form":form,
#        "title":"Add Product To Store",
#        "button":"Add"
#        }
#     template_name='main/company/form.html'
   
        
    
#     return render(request, template_name,context)
 

 

#Api Views-------------------------------------------------------------------------------------------------

class ApiCompanyList(APIView):
    """
    List all companys, or create a new company.
    """
    def get(self, request, format=None):
        companys = Company.objects.all()
        serializer = CompanySerializers(companys, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = CompanySerializers(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ApiCompanyDetail(APIView):
    """
    Retrieve, update or delete a Company instance.
    """
    def get_object(self, slug):
        try:
            return Company.objects.get(slug=slug)
        except Company.DoesNotExist:
            raise Http404

    def get(self, request, slug, format=None):
        company = self.get_object(slug)
        serializer = CompanySerializers(company)
        return Response(serializer.data)

    def put(self, request, slug, format=None):
        company = self.get_object(slug)
        serializer = CompanySerializer(company, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, slug, format=None):
        company = self.get_object(slug)
        company.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

product/templates/main/company/delivered.html
{% extends 'main/base.html' %}
{% load static %}
{% block company %}
<div class="company-head"  style="background-image: {% if object.cover %}url('{{object.cover.url}}'){% else %} url('{% static 'img/product-img/pro-big-1.jpg' %}'){% endif %};">
    
    
    
        
      <div class="company-logo">
        {% if object.logo %}
        <img  src="{{object.logo.url}}"  >
        {% else %}
        
        <h1 style="text-align: center; color: #717571;">{{object.name|title}}</h1>
        {% endif %}
    </div>
    {% if object == user.company %}
    <div class="profile-link">
        <a class="" href="{% url 'products:create'  %}"> <i class="icon ion-plus"></i><span>Add Product</span></a><a class="" href="{% url 'company:update'  %}">  
				  <i class="ion ion-edit"
	></i>	<span>Update Store Info</span>	</a>
    </div>
  {% endif %}
    
   
</div>
{% endblock company %}
{% block content %}
{{block.super}}





<section class="courses">
    <div class="row ">
        <div class="col-12">
          
                    
                    <a href="/{{object.slug}}/account/" class="btn btn-primary" style=" float:left;  border-color: #30323A; margin: 5px;">My Company Finance</a>
                    <a href="/{{object.slug}}/requested/" class="btn btn-main" style="float:left; border-color:#30323A;; margin: 5px;;">Recent Orders</a>
                    <a href="/{{object.slug}}/delivered/" class="btn btn-main" style=" float:left;background-color: #30323A;  border-color: #30323A; margin: 5px;">Delivered Orders</a>
                    <a href="/{{object.slug}}/returned/" class="btn btn-main" style="float:left; border-color:#30323A;; margin: 5px;;">Returned Orders</a>
               
                <!-- Sorting -->
               
        </div>
    </div>
<div id="store">
    <!-- row -->
    
    <div class="sale-record">
        
    <!-- Single Product Area -->
   
    <!-- Single Product Area -->
    {% for product in delivered %}
      <div class=" ">
                <div class=" " style="width: 100%; float: none;">
                    <div class="" style="float: left; width: 30%;">
                        
     
                        <img src="{{product.product.image.url}}" alt="" style="height: 150px;">
                    </div>
                    <div class="">
                        <h5 class="product-price" ><b>{{product.name}} </b> </h5>
                        <h5 class="product-price" > <b> Package Number:{{product.package_number}}  </b> </h5>
                        <h6 class="product-name"style="float: right; padding:5px;">Status:  {{product.status}}  </h6>
                        
                        <h6 class="product-name" style="">Price: &#8358;{{product.price}}</h6>
                        <h6 class="product-name" style="">Quantity: {{product.quantity}}</h6>
                        <h6 class="product-name" style=" padding:5px;"> Date Requested: {{product.package_time}}  </h6>
                        <h6 class="product-name"style=" padding:5px;"> Date Shipped: {{product.collected_time}}  </h6>
                        <h6 class="product-name"style=" padding:5px;"> Date Delivered: {{product.delivery_time}}  </h6>
                        <h6 class="product-name"style=" padding:5px;"> Date Returned: {{product.returned_time}}   </h6>
                        
                        
                    </div>
                </div>
            </div>
            <br/>
{% endfor %}
    </div>
</div>
</section>


    <div class="aside">
        <h3 class="aside-title">Top Sales</h3>
        <!-- widget product -->
        
        <div class="product product-widget">
            {% for product in object_list %}
            <a href="/products/{{product.slug}}">
            <div >
                <img src="{{product.image.url}}" alt="">
            </div>
            <div class="product-body">
                <h2 class="product-name"><a href="/products/{{product.slug}}">{{product.name}}</a></h2>
                <h3 class="product-price">${{product.price}} <del class="product-old-price">${{product.discounted_from}}</del></h3>
                
            </div>
            </a>
            {% endfor %}
            
            
        </div>
        <!-- /widget product -->
</div>
        
{% endblock content %}

product/templates/main/company/profile-acc.html
{% extends 'main/base.html' %} {% load static %} {% block company %}
<div
  class="company-head"
  style="background-image: {% if object.cover %}url('{{object.cover.url}}'){% else %} url('{% static 'img/product-img/background1.webp' %}'){% endif %};"
>
  <div class="company-logo">
    {% if object.logo %}
    <img src="{{object.logo.url}}" />
    {% else %}

    <h1 style="text-align: center; color: #717571">{{object.name|title}}</h1>
    {% endif %}
  </div>
  {% if object == user.company %}
  <div class="profile-link">
    <a class="" href="{% url 'products:create'  %}">
      <i class="icon ion-plus"></i><span>Add Product</span></a
    ><a class="" href="{% url 'company:update'  %}">
      <i class="ion ion-edit"></i> <span>Update Store Info</span>
    </a>
  </div>
  {% endif %}
</div>
{% endblock company %} {% block content %} {{block.super}}

<section class="courses">
  <div class="row">
    <div class="col-12">
      <a
        href="/{{object.slug}}/account/"
        class="btn btn-primary"
        style="
          float: left;
          background-color: #30323a;
          border-color: #30323a;
          margin: 5px;
        "
        >My Company Finance</a
      >
      <a
        href="/{{object.slug}}/requested/"
        class="btn btn-main"
        style="float: left; border-color: #30323a; margin: 5px"
        >Recent Orders</a
      >
      <a
        href="/{{object.slug}}/delivered/"
        class="btn btn-main"
        style="float: left; border-color: #30323a; margin: 5px"
        >Delivered Orders</a
      >
      <a
        href="/{{object.slug}}/returned/"
        class="btn btn-main"
        style="float: left; border-color: #30323a; margin: 5px"
        >Returned Orders</a
      >

      <!-- Sorting -->
    </div>
  </div>

  <!-- row -->
  <div class="store">
    <div class="row">
      <!-- <h4 class=" ">CUSTOMERS ({{instance.customers.all.count}} )</h4> -->
      <div class="row">
        <div class="col-12">
          <div
            class="product-topbar d-xl-flex align-items-end justify-content-between"
          >
            <!-- Total Products -->
            <div class="total-products">
              <h2><a href="#">CUSTOMERS ({{customers.all.count}} )</a></h2>
            </div>
            <!-- Sorting -->
          </div>
        </div>
      </div>
      <div class="cart-table clearfix" style="overflow-x: scroll">
        <table
          class="table table-responsive"
          style="overflow: hidden; outline: currentcolor none medium"
        >
          <thead>
            <tr style="background-color: #f5f7fa">
              <th>Name</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            {% for customer in customers %}
            <tr>
              <td>{{customer.username}}</td>
              <td>
                <label class="badge badge-gradient-success"
                  >{{customer.email}}</label
                >
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

<div class="aside">
  <label class="aside-title">{{object.name}} Website Link</label>
  <!-- widget product -->

  <div class="product product-widget">
    <input class="form-control" value="ojaa.me/{{object.slug}}/" readonly />
  </div>
  <label class="aside-title">Bank Details</label>
  <!-- widget product -->

  <div class="product product-widget">
    <h5>Name: {{object.bankaccountdetail.acc_name}}</h5>
    <h5>Number: {{object.bankaccountdetail.acc_number}}</h5>
    <h5>Bank: {{object.bankaccountdetail.bank}}</h5>
  </div>
  <h3 class="aside-title">Last Purchase</h3>
  <!-- widget product -->

  <div class="product product-widget">
    <h1>&#8358;{{account.last_cash_recieved}}</h1>
  </div>
  <!-- /widget product -->
  <h3 class="aside-title">Total Income</h3>
  <!-- widget product -->

  <div class="product product-widget">
    <h2>&#8358;{{object.account.total_income}}</h2>
  </div>
  <!-- /widget product -->
  <h3 class="aside-title">Ledger Balance</h3>
  <!-- widget product -->

  <div class="product product-widget">
    <h2>&#8358;{{object.account.ledger_balance}}</h2>
  </div>
  <!-- /widget product -->
  <h3 class="aside-title">Avaliable Balance</h3>
  <!-- widget product -->

  <div class="product product-widget">
    <h2>&#8358;{{object.account.available_balance}}</h2>
  </div>

  <!-- /widget product -->

  <button id="cashout-btn" name="addtocart" value="5" class="btn amado-btn">
    Cash out
  </button>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li class="{{message.tags}}">{{message}}</li>
    {% endfor %}
  </ul>
  {% endif %}
  <div id="cashout-form" class="">
    <h3 class="aside-title cashout">Cashout</h3>
    <!-- widget product -->

    <div class="product product-widget">
      <form
        action="{% url 'referral:withdraw' %}"
        class="form-group"
        method="POST"
      >
        {% csrf_token %}
        <label>Ammount Requested</label>
        {% if form.error %} {{form.errors}} {% endif %}

        <p id="id_ammount_alert"></p>
        <input
          type="hidden"
          name=""
          id="savings_balance"
          value="{{account.available_balance}}"
        />
        <input
          type="text"
          id="id_ammount_requested"
          maxlength="240"
          name="ammount_request"
          required
          class="form-control"
        />
        <button type="submit" class="btn amado-btn">Cash out</button>
      </form>
    </div>
  </div>
  <!-- /widget product -->
</div>

{% endblock content %} {% block formadjust %}
<script>
  $.ajax();
</script>
<script>
  $("#cashout-btn").on("click", function () {
    $("#cashout-form").addClass("open");
    $("#cashout-btn").addClass("close");
  });
  var withdrawAmmount = $("#id_ammount_alert");
  var savingsBalance = $("#savings_balance").val();
  var inputArea = $("#id_ammount_requested");
  console.log(savingsBalance);

  inputArea.keyup(function () {
    var withdrawAmmountValue = $(this).val();
    if (parseInt(withdrawAmmountValue) >= savingsBalance) {
      var x =
        "<p> You Don't have upto " +
        withdrawAmmountValue +
        " in your account</p>";
      document.getElementById("id_ammount_alert").innerHTML = x;
    }
  });

  if (parseInt(withdrawAmmount) >= savingsBalance) {
    alert("Insufficient Balance");
  }
</script>
<!-- <script>
    var endpoint_sale='/referral/sale/api/'

$.ajax({
        type:'GET',
        url:endpoint_sale,
        success:function(data){
            var dayList=[];
            var monthList=[];
            var totalPrice=[];
            $.each(data,function(i,datum){
                totalPrice.push(datum.total_price)
                var date=datum.date;
                var d=new Date(date);
                dayList.push(d.getDate());
                monthList.push(d.getMonth()+1);
                
            });
            console.log(dayList);
            console.log(monthList);
            console.log(totalPrice);
            
            
            
        },
        error:function(){
            alert('error loading review');
        }
        
    });
var endpoint='/referral/s/api/'
$.ajax({
        type:'GET',
        url:endpoint,
        success:function(data){
            lab=data.days
            labels=["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"]
            $('#year').on('click', function(){
                labels=["January","Febuary","March","April","May","June","July","August","September","October","November","December"]
            });
            DataCustomers=data.customers;
            defaultData=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
            // personal function
            for(const[i, x] of lab.entries()){
                var d=new Date(x);
                var day=d.getDate()-1;
                var month_=d.getMonth()+1;
                var year=d.getFullYear();
                defaultData[day]=DataCustomers[i];
            }
            
            setChart();
            
            
        },
        error:function(){
            alert('error loading review');
        }
        
    });
function setChart(){
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: labels,
        datasets: [{
            label: 'No of Sales',
            data: defaultData,
            backgroundColor: [
                
                'rgba(255, 206, 86, 0.2)'
               
            ],
            borderColor: [
                'rgba(255, 206, 86, 1)'
               
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
}

function setCharts(){
var ctx = document.getElementById('myChart2');

var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: labels,
        datasets: [{
            label: 'No of Referred customers',
            data: defaultData,
            backgroundColor: [
                
                'rgba(255, 206, 86, 0.2)'
               
            ],
            borderColor: [
                'rgba(255, 206, 86, 1)'
               
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
}
</script> -->

{% endblock formadjust %}